-- Reference schema of conformance/widget. Normative for the fixture: every SDK's
-- examples/widget creates exactly these tables and columns (in its own migration tool's
-- file layout), because conformance/fixtures.yaml observes them with SQL.
-- Rules it follows (be-protocol P11.2, P11.5-P11.8): unqualified names, no OWNER / GRANT /
-- SET / CREATE SCHEMA, no role or schema literal, no date-literal partitions (the platform
-- migration creates the partition windows from lifecycle.yaml), uuid keys generated by the
-- application, created_at = IDTime(id) on partitioned tables, NUMERIC with precision.

CREATE TABLE widget_kinds (
    code       TEXT PRIMARY KEY,
    title      TEXT NOT NULL,
    max_lines  INT  NOT NULL
);
INSERT INTO widget_kinds (code, title, max_lines) VALUES
    ('STD', 'Standard', 10),
    ('BIG', 'Big', 100)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE widget_owners (
    id            UUID        PRIMARY KEY,
    sub           TEXT        NOT NULL UNIQUE,      -- platform sub
    display_name  TEXT        NOT NULL,
    phone         TEXT        NOT NULL DEFAULT '',
    email         TEXT        NOT NULL DEFAULT '',
    updated_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE widgets (
    id               UUID          NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL,          -- = IDTime(id)
    legal_entity_id  TEXT          NOT NULL,
    number           TEXT          NOT NULL,          -- WIDGET_NO_FORMAT, gapped
    document_date    DATE          NOT NULL,          -- business date in the legal entity's zone
    kind_code        TEXT          NOT NULL,
    name             TEXT          NOT NULL,
    region           TEXT          NOT NULL,          -- resource dimension "region"
    owner_id         TEXT          NOT NULL,          -- owner dimension
    dept_path        TEXT          NOT NULL DEFAULT '', -- org dimension; '' = no department (R60)
    status           TEXT          NOT NULL CHECK (status IN ('DRAFT', 'APPROVING', 'APPROVED', 'SUSPENDED')),
    currency         CHAR(3)       NOT NULL,
    price            NUMERIC(19,6) NOT NULL,
    quantity         NUMERIC(19,6) NOT NULL,
    amount           NUMERIC(19,4) NOT NULL,
    reservation_id   TEXT          NOT NULL DEFAULT '',
    deadline_at      TIMESTAMPTZ,                     -- set while APPROVING
    approved_at      TIMESTAMPTZ,
    touch_count      BIGINT        NOT NULL DEFAULT 0,
    attachments      JSONB         NOT NULL DEFAULT '[]', -- [{attachment_id, file_name, content_type, size_bytes}]
    version          BIGINT        NOT NULL,          -- aggregate version
    updated_at       TIMESTAMPTZ   NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
-- A unique number per legal entity cannot be enforced across partitions of a table partitioned
-- by created_at; the runtime's unpartitioned besdk_number_allocations enforces it (P11.10). The
-- index serves look-ups by number.
CREATE INDEX widgets_number ON widgets (legal_entity_id, number);
CREATE INDEX widgets_list ON widgets (created_at DESC, id DESC);
CREATE INDEX widgets_approving ON widgets (deadline_at) WHERE status = 'APPROVING';
CREATE INDEX widgets_reservation ON widgets (reservation_id) WHERE reservation_id <> '';

CREATE TABLE widget_lines (
    id           UUID          NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL,              -- = the widget's created_at (follows: widgets)
    widget_id    UUID          NOT NULL,
    line_no      INT           NOT NULL,
    description  TEXT          NOT NULL,
    quantity     NUMERIC(19,6) NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE INDEX widget_lines_widget ON widget_lines (widget_id, line_no);

CREATE TABLE widget_ledger (
    id               UUID          NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL,
    legal_entity_id  TEXT          NOT NULL,
    widget_id        UUID          NOT NULL,
    entry_no         TEXT          NOT NULL,          -- WIDGET_LEDGER_NO_FORMAT, gap-free per legal entity and period
    posting_date     DATE          NOT NULL,
    fiscal_period    TEXT          NOT NULL,          -- period key, e.g. 2026-P07
    currency         CHAR(3)       NOT NULL,
    amount           NUMERIC(19,4) NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE INDEX widget_ledger_widget ON widget_ledger (widget_id);

CREATE TABLE widget_audit (
    id          UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    actor_sub   TEXT        NOT NULL DEFAULT '',      -- '' for background work
    caller      TEXT        NOT NULL,                 -- user:<sub> | svc:<be-caller> | system
    action      TEXT        NOT NULL,                 -- created | approved | reverted | touched | daily_summary | …
    widget_id   TEXT        NOT NULL DEFAULT '',
    details     JSONB       NOT NULL DEFAULT '{}',
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE INDEX widget_audit_widget ON widget_audit (widget_id, created_at);

CREATE TABLE widget_jobs (
    id          UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    widget_id   TEXT        NOT NULL,
    kind        TEXT        NOT NULL CHECK (kind IN ('approved', 'exception')),
    state       TEXT        NOT NULL CHECK (state IN ('PENDING', 'SENT', 'DEAD')),
    attempts    INT         NOT NULL DEFAULT 0,
    last_error  TEXT        NOT NULL DEFAULT '',
    updated_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE INDEX widget_jobs_widget ON widget_jobs (widget_id);

CREATE TABLE owner_snapshots (
    owner_id      TEXT          PRIMARY KEY,
    display_name  TEXT          NOT NULL,
    credit_limit  NUMERIC(19,4) NOT NULL,
    currency      CHAR(3)       NOT NULL,
    version       BIGINT        NOT NULL,             -- upstream aggregate version; upserts guard on it (P15.1)
    synced_at     TIMESTAMPTZ   NOT NULL
);
