-- GENERATED by scripts/gen-platform-migration.mjs from protocol/ddl (be-protocol v1.0.0-rc.1 c72c509d7e1ae74f0c3e3d1cc0c61010b3549aa8); do not edit.
-- be-sdk-ts platform version 1: every besdk_* table and platform function of the reference DDL except
-- 07-authz-projection.sql (only with declared resources) and be_bus.sql (database initialisation).
-- Up Migration

-- ===== 01-platform-version.sql =====
-- be-protocol 1.0 reference DDL: platform version (P11.3)
--
-- Normative. Every besdk_* table lives in the component's own schema and is created by the
-- runtime's platform migration, which runs in the migration step logged in as the owner role
-- (PG_OWNER_USER), so the owner owns it. The runtime role (PG_USER) gets DML on it through the
-- schema's default privileges, which the project's database initialisation sets (never a GRANT
-- here). Names are unqualified and resolve through search_path = PG_SCHEMA (P11.2). Component SQL
-- never reads or writes a besdk_* table (gate platform-table-scan). Files are applied in name
-- order; every statement is idempotent. PostgreSQL >= 14.

CREATE TABLE IF NOT EXISTS besdk_platform_version (
    component  TEXT        PRIMARY KEY,               -- the component ID that owns this schema
    version    INT         NOT NULL,                  -- the platform migration version applied
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== 02-outbox.sql =====
-- be-protocol 1.0 reference DDL: event outbox (P12.1, P12.15)
--
-- Partitioned by created_at, one partition per week, created and dropped by the lifecycle engine
-- (class platform: a partition is dropped 14 days after all its rows are PUBLISHED). The platform
-- migration creates the current window (P16.6); this file creates the parent only.

CREATE TABLE IF NOT EXISTS besdk_outbox (
    id                UUID        NOT NULL,              -- UUIDv7 = ce-id = Nats-Msg-Id
    created_at        TIMESTAMPTZ NOT NULL,              -- = the timestamp embedded in id
    subject           TEXT        NOT NULL,              -- ce-type
    aggregate_type    TEXT        NOT NULL,              -- ce-aggregatetype, from the contract
    aggregate_id      TEXT        NOT NULL,              -- ce-subject
    aggregate_version BIGINT      NOT NULL,              -- ce-aggregateversion
    occurred_at       TIMESTAMPTZ NOT NULL,              -- ce-time
    traceparent       TEXT        NOT NULL DEFAULT '',
    causation_id      TEXT        NOT NULL DEFAULT '',   -- ce-causationid
    hop_count         INT         NOT NULL DEFAULT 0,    -- ce-hopcount
    headers           JSONB       NOT NULL DEFAULT '{}', -- other ce-* attributes, e.g. {"ce-legalentity": "LE01"}
    payload           JSONB       NOT NULL,
    status            TEXT        NOT NULL DEFAULT 'PENDING'
                      CHECK (status IN ('PENDING', 'SENDING', 'PUBLISHED')),
    attempts          INT         NOT NULL DEFAULT 0,
    next_attempt_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_until     TIMESTAMPTZ,
    published_at      TIMESTAMPTZ,
    last_error        TEXT        NOT NULL DEFAULT '',
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX IF NOT EXISTS besdk_outbox_due ON besdk_outbox (next_attempt_at) WHERE status <> 'PUBLISHED';

-- Claim, each replica, each round (P10.9):
--   UPDATE besdk_outbox SET status = 'SENDING', claimed_until = now() + interval '30 seconds',
--                           attempts = attempts + 1
--    WHERE (id, created_at) IN (
--          SELECT id, created_at FROM besdk_outbox
--           WHERE (status = 'PENDING' AND next_attempt_at <= now())
--              OR (status = 'SENDING' AND claimed_until < now())
--           ORDER BY created_at, id
--           LIMIT 256
--           FOR UPDATE SKIP LOCKED)
--   RETURNING *;
-- After the broker acknowledged:  UPDATE … SET status = 'PUBLISHED', published_at = now(), claimed_until = NULL
-- After a failed publish:         UPDATE … SET status = 'PENDING', next_attempt_at = now() + <backoff 1s..1min>,
--                                              claimed_until = NULL, last_error = <redacted text>

-- ===== 03-event-cursor.sql =====
-- be-protocol 1.0 reference DDL: consumer cursor (P12.6)
--
-- Not partitioned, on purpose: a partition key in the primary key would let two concurrent
-- deliveries both insert. Bounded by retention: rows unseen for 30 days are deleted (P12.15).

CREATE TABLE IF NOT EXISTS besdk_event_cursor (
    consumer       TEXT        NOT NULL DEFAULT '',    -- projection name; '' is the component's default
    aggregate_type TEXT        NOT NULL,
    aggregate_id   TEXT        NOT NULL,
    version        BIGINT      NOT NULL,
    event_id       TEXT        NOT NULL,
    seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (consumer, aggregate_type, aggregate_id)
);

CREATE INDEX IF NOT EXISTS besdk_event_cursor_seen ON besdk_event_cursor (seen_at);

-- Decide "new or stale" and advance, in the handler's transaction; no row returned = skip:
--   INSERT INTO besdk_event_cursor (consumer, aggregate_type, aggregate_id, version, event_id)
--   VALUES ($1, $2, $3, $4, $5)
--   ON CONFLICT (consumer, aggregate_type, aggregate_id) DO UPDATE
--      SET version = EXCLUDED.version, event_id = EXCLUDED.event_id, seen_at = now()
--    WHERE besdk_event_cursor.version < EXCLUDED.version
--   RETURNING 1;

-- ===== 04-idempotency.sql =====
-- be-protocol 1.0 reference DDL: command idempotency (P13)
--
-- Not partitioned; rows are deleted after expires_at (30 days).

CREATE TABLE IF NOT EXISTS besdk_idempotency (
    caller          TEXT        NOT NULL,                -- user:<sub> | svc:<component ID> | system
    idempotency_key TEXT        NOT NULL,
    command         TEXT        NOT NULL,                -- permission key or full rpc name
    target          TEXT        NOT NULL DEFAULT '',     -- aggregate ID; '' for a create
    request_hash    BYTEA       NOT NULL,                -- SHA-256 of the JCS-canonical fingerprint fields
    status          TEXT        NOT NULL DEFAULT 'CLAIMED' CHECK (status IN ('CLAIMED', 'DONE')),
    result          JSONB,                               -- {"status": <http>, "body": …} once DONE
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,                -- created_at + 30 days
    PRIMARY KEY (caller, idempotency_key)
);

CREATE INDEX IF NOT EXISTS besdk_idempotency_expires ON besdk_idempotency (expires_at);

-- ===== 05-jobs.sql =====
-- be-protocol 1.0 reference DDL: background jobs and reconcilers (P14)
--
-- holder = '<component ID>/<instance id>' for the in-process scheduler, '<component ID>/job-run:<instance id>'
-- for a one-shot `job run <name>` (P14.8): both claim through the same rows, so a slot or a lease is
-- taken once whoever triggers it. Not partitioned; done queue rows and old slots are deleted after
-- retention by the runtime's cleanup singleton.

CREATE TABLE IF NOT EXISTS besdk_job_lease (
    name       TEXT        PRIMARY KEY,
    holder     TEXT        NOT NULL,
    epoch      BIGINT      NOT NULL DEFAULT 0,           -- fencing token, +1 on every takeover
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS besdk_job_slot (
    name       TEXT        NOT NULL,
    slot_at    TIMESTAMPTZ NOT NULL,                     -- the scheduled instant of the slot
    holder     TEXT        NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    done_at    TIMESTAMPTZ,
    result     TEXT,
    PRIMARY KEY (name, slot_at)
);

CREATE TABLE IF NOT EXISTS besdk_job_queue (
    id           UUID        PRIMARY KEY,                -- UUIDv7
    kind         TEXT        NOT NULL,
    args         JSONB       NOT NULL,
    unique_key   TEXT,                                   -- optional de-duplication key
    run_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempts     INT         NOT NULL DEFAULT 0,
    max_attempts INT         NOT NULL,
    state        TEXT        NOT NULL DEFAULT 'ready' CHECK (state IN ('ready', 'running', 'done', 'dead')),
    lease_until  TIMESTAMPTZ,
    last_error   TEXT        NOT NULL DEFAULT '',
    traceparent  TEXT        NOT NULL DEFAULT '',
    causation_id TEXT        NOT NULL DEFAULT '',
    hop_count    INT         NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ
);

-- one live job per key; a done job frees the key
CREATE UNIQUE INDEX IF NOT EXISTS besdk_job_queue_unique ON besdk_job_queue (kind, unique_key)
    WHERE unique_key IS NOT NULL AND state <> 'done';
CREATE INDEX IF NOT EXISTS besdk_job_queue_due ON besdk_job_queue (kind, run_at)
    WHERE state IN ('ready', 'running');

CREATE TABLE IF NOT EXISTS besdk_reconcile (
    name        TEXT        NOT NULL,                    -- the reconciler's name
    item_id     TEXT        NOT NULL,
    attempts    INT         NOT NULL DEFAULT 0,
    next_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_until TIMESTAMPTZ,
    last_error  TEXT        NOT NULL DEFAULT '',
    PRIMARY KEY (name, item_id)
);

CREATE INDEX IF NOT EXISTS besdk_reconcile_due ON besdk_reconcile (name, next_at);

-- ===== 06-snapshots-and-backfills.sql =====
-- be-protocol 1.0 reference DDL: snapshot backfill progress (P15.3) and resumable backfills (P11.4)

CREATE TABLE IF NOT EXISTS besdk_snapshot_sync (
    name         TEXT        PRIMARY KEY,                -- the snapshot's name
    status       TEXT        NOT NULL DEFAULT 'PENDING', -- PENDING | RUNNING | DONE
    cursor       TEXT        NOT NULL DEFAULT '',        -- the upstream List cursor to resume from
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS besdk_backfill (
    name       TEXT        PRIMARY KEY,                  -- the backfill step's name
    cursor     TEXT        NOT NULL DEFAULT '',
    done       BOOLEAN     NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===== 08-number-series.sql =====
-- be-protocol 1.0 reference DDL: document numbers (P11.10)

CREATE TABLE IF NOT EXISTS besdk_number_series (
    series     TEXT        NOT NULL,                     -- e.g. sales_order, voucher
    scope      TEXT        NOT NULL DEFAULT '',          -- the legal entity id, or another declared scope
    period     TEXT        NOT NULL DEFAULT '',          -- period key from the business date (vouchers: the accounting period)
    next_value BIGINT      NOT NULL DEFAULT 1,
    gapless    BOOLEAN     NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (series, scope, period)
);

-- Gap-free, in the document's own transaction (after the idempotency claim succeeded):
--   INSERT INTO besdk_number_series (series, scope, period, gapless) VALUES ($1, $2, $3, true)
--   ON CONFLICT DO NOTHING;
--   UPDATE besdk_number_series SET next_value = next_value + 1, updated_at = now()
--    WHERE series = $1 AND scope = $2 AND period = $3
--   RETURNING next_value - 1;
-- Gapped, in a short transaction of its own, reserving a block of $4 numbers:
--   … SET next_value = next_value + $4 … RETURNING next_value - $4;

-- Uniqueness of the numbers themselves (P11.10). Unpartitioned on purpose: a unique index on a
-- partitioned document table must contain its partition key, so (legal_entity_id, number) could not
-- be unique across partitions there. The runtime inserts every formatted number in the document's
-- own transaction; a repeat fails that transaction with 23505 on this table (a series
-- misconfiguration, surfaced as INTERNAL), and a rollback frees the number. legal_entity_id is the
-- series' scope ('' for a series not scoped by legal entity). Rows are kept as long as the
-- component's documents may exist (class platform; never dropped by the lifecycle engine in 1.0).
CREATE TABLE IF NOT EXISTS besdk_number_allocations (
    legal_entity_id TEXT        NOT NULL,
    series          TEXT        NOT NULL,
    number          TEXT        NOT NULL,                -- the formatted document number
    document_id     TEXT        NOT NULL,                -- the document's id, for look-ups and audits
    allocated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (legal_entity_id, series, number)
);

-- In the document's transaction, right after the number was taken from besdk_number_series:
--   INSERT INTO besdk_number_allocations (legal_entity_id, series, number, document_id)
--   VALUES ($1, $2, $3, $4);

-- ===== 09-lifecycle.sql =====
-- be-protocol 1.0 reference DDL: data lifecycle engine (P16)

CREATE TABLE IF NOT EXISTS besdk_lifecycle_units (
    table_name      TEXT        NOT NULL,
    unit_key        TEXT        NOT NULL,                -- partition name, or the anchor month of a row unit
    range_from      TIMESTAMPTZ,
    range_to        TIMESTAMPTZ,
    list_value      TEXT,                                -- LIST partitions (e.g. an accounting period)
    state           TEXT        NOT NULL
                    CHECK (state IN ('ACTIVE', 'BLOCKED', 'SEALED', 'EXPORTING', 'EXPORTED', 'VERIFIED',
                                     'COLD_PENDING_DROP', 'COLD', 'THAWED', 'DESTROYED')),
    rows            BIGINT,
    min_id          TEXT,
    max_id          TEXT,
    unit_digest     BYTEA,                               -- SHA-256 of the canonical encoding (P16)
    chain_digest    BYTEA,                               -- SHA-256(previous chain || unit_digest)
    manifest_url    TEXT,
    manifest_sha256 BYTEA,
    sealed_at       TIMESTAMPTZ,
    cold_at         TIMESTAMPTZ,
    thawed_until    TIMESTAMPTZ,
    destroyed_at    TIMESTAMPTZ,
    blocked_reason  TEXT,
    version         BIGINT      NOT NULL DEFAULT 1,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (table_name, unit_key)
);

-- append-only, kept forever; protected by besdk_sealed_guard from creation
CREATE TABLE IF NOT EXISTS besdk_lifecycle_log (
    id         BIGINT      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    table_name TEXT,
    unit_key   TEXT,
    action     TEXT        NOT NULL,
    actor      TEXT,
    detail     JSONB       NOT NULL
);

CREATE TABLE IF NOT EXISTS besdk_holds (
    hold_id     TEXT        PRIMARY KEY,
    scope       JSONB       NOT NULL,                    -- which tables / units / subjects the hold covers
    reason      TEXT        NOT NULL,
    placed_by   TEXT        NOT NULL,
    placed_at   TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS besdk_erasures (
    request_id  TEXT        PRIMARY KEY,
    subject     TEXT        NOT NULL,                    -- subject type, e.g. customer
    subject_id  TEXT        NOT NULL,                    -- opaque id only, never the erased content
    received_at TIMESTAMPTZ NOT NULL,
    applied_at  TIMESTAMPTZ,
    result      JSONB
);

CREATE TABLE IF NOT EXISTS besdk_exports (
    job_id       TEXT        PRIMARY KEY,
    requested_by TEXT        NOT NULL,
    spec         JSONB       NOT NULL,                   -- {table, from, to, filter, format}
    state        TEXT        NOT NULL,
    result_url   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ
);

-- The guard installed on sealed partitions (BEFORE UPDATE OR DELETE … FOR EACH ROW and
-- BEFORE TRUNCATE … FOR EACH STATEMENT) and on besdk_lifecycle_log. SQLSTATE BE001 is mapped by the
-- runtime to FAILED_PRECONDITION / UNIT_SEALED (P16.5).
CREATE OR REPLACE FUNCTION besdk_sealed_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION USING ERRCODE = 'BE001',
        MESSAGE = format('UNIT_SEALED: %s is sealed', TG_TABLE_NAME);
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
                    WHERE c.oid = to_regclass('besdk_lifecycle_log') AND t.tgname = 'besdk_lifecycle_log_append_only') THEN
        CREATE TRIGGER besdk_lifecycle_log_append_only
            BEFORE UPDATE OR DELETE ON besdk_lifecycle_log
            FOR EACH ROW EXECUTE FUNCTION besdk_sealed_guard();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
                    WHERE c.oid = to_regclass('besdk_lifecycle_log') AND t.tgname = 'besdk_lifecycle_log_no_truncate') THEN
        CREATE TRIGGER besdk_lifecycle_log_no_truncate
            BEFORE TRUNCATE ON besdk_lifecycle_log
            FOR EACH STATEMENT EXECUTE FUNCTION besdk_sealed_guard();
    END IF;
END;
$$;

-- ===== 10-lifecycle-functions.sql =====
-- be-protocol 1.0 reference DDL: the DDL the runtime may perform (P10.12, P16.2)
--
-- The runtime role (PG_USER) has DML only and never logs in as the owner (PG_OWNER_USER). The few
-- DDL steps the lifecycle engine must take while the service runs go through these functions,
-- which the platform migration creates as the owner. They are SECURITY DEFINER with the
-- search_path pinned to the schema they were created in (SET search_path FROM CURRENT: no schema
-- literal), act only on tables of that schema, and quote every identifier. Only roles with USAGE
-- on the schema can reach them: the owner and the runtime role (in a shell, after SET LOCAL ROLE).
-- DETACH PARTITION … CONCURRENTLY cannot run inside a function or a transaction block; it is used
-- only by the migration step. At run time an expired platform or queue partition is detached with
-- a plain DETACH under the caller's short lock_timeout.

-- create one RANGE partition [p_from, p_to) of p_parent, named p_name; idempotent
CREATE OR REPLACE FUNCTION besdk_ensure_range_partition(p_parent text, p_name text, p_from timestamptz, p_to timestamptz)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_partitioned_table pt JOIN pg_class c ON c.oid = pt.partrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE n.nspname = v_schema AND c.relname = p_parent AND pt.partstrat = 'r') THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a range-partitioned table of this schema', p_parent);
    END IF;
    IF p_name !~ ('^' || p_parent || '_[a-z0-9_]+$') THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('partition name %s must start with %s_', p_name, p_parent);
    END IF;
    IF to_regclass(format('%I.%I', v_schema, p_name)) IS NOT NULL THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TABLE %I.%I (LIKE %I.%I INCLUDING DEFAULTS INCLUDING CONSTRAINTS)', v_schema, p_name, v_schema, p_parent);
    EXECUTE format('ALTER TABLE %I.%I ATTACH PARTITION %I.%I FOR VALUES FROM (%L) TO (%L)', v_schema, p_parent, v_schema, p_name, p_from, p_to);
    RETURN true;
END;
$$;

-- create one LIST partition of p_parent for p_value (an accounting period, opened by a command); idempotent
CREATE OR REPLACE FUNCTION besdk_ensure_list_partition(p_parent text, p_name text, p_value text)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_partitioned_table pt JOIN pg_class c ON c.oid = pt.partrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE n.nspname = v_schema AND c.relname = p_parent AND pt.partstrat = 'l') THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a list-partitioned table of this schema', p_parent);
    END IF;
    IF p_name !~ ('^' || p_parent || '_[a-z0-9_]+$') THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('partition name %s must start with %s_', p_name, p_parent);
    END IF;
    IF to_regclass(format('%I.%I', v_schema, p_name)) IS NOT NULL THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TABLE %I.%I (LIKE %I.%I INCLUDING DEFAULTS INCLUDING CONSTRAINTS)', v_schema, p_name, v_schema, p_parent);
    EXECUTE format('ALTER TABLE %I.%I ATTACH PARTITION %I.%I FOR VALUES IN (%L)', v_schema, p_parent, v_schema, p_name, p_value);
    RETURN true;
END;
$$;

-- install the sealed-unit guard on one table or partition of this schema; idempotent
CREATE OR REPLACE FUNCTION besdk_seal_table(p_table text)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
    v_oid    regclass := to_regclass(format('%I.%I', current_schema(), p_table));
BEGIN
    IF v_oid IS NULL OR p_table LIKE 'besdk\_%' THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a sealable table of this schema', p_table);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = v_oid AND tgname = 'besdk_sealed_rows') THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TRIGGER besdk_sealed_rows BEFORE UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION besdk_sealed_guard()', v_schema, p_table);
    EXECUTE format('CREATE TRIGGER besdk_sealed_truncate BEFORE TRUNCATE ON %I.%I FOR EACH STATEMENT EXECUTE FUNCTION besdk_sealed_guard()', v_schema, p_table);
    RETURN true;
END;
$$;

-- detach (plain, not CONCURRENTLY) and drop one partition of p_parent; idempotent
CREATE OR REPLACE FUNCTION besdk_drop_partition(p_parent text, p_name text)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
    v_part   regclass := to_regclass(format('%I.%I', current_schema(), p_name));
BEGIN
    IF v_part IS NULL THEN
        RETURN false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_inherits i WHERE i.inhrelid = v_part
                      AND i.inhparent = to_regclass(format('%I.%I', v_schema, p_parent))) THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a partition of %s', p_name, p_parent);
    END IF;
    EXECUTE format('ALTER TABLE %I.%I DETACH PARTITION %I.%I', v_schema, p_parent, v_schema, p_name);
    EXECUTE format('DROP TABLE %I.%I', v_schema, p_name);
    RETURN true;
END;
$$;

-- thaw, step 1: create the table that will hold one cold unit again, detached and empty, shaped like
-- p_parent; the runtime then loads the unit's rows into it with plain INSERTs (it has DML on the
-- table through the schema's default privileges, because the table is created by the owner); idempotent
CREATE OR REPLACE FUNCTION besdk_thaw_create(p_parent text, p_name text)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_partitioned_table pt JOIN pg_class c ON c.oid = pt.partrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE n.nspname = v_schema AND c.relname = p_parent) OR p_parent LIKE 'besdk\_%' THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a partitioned business table of this schema', p_parent);
    END IF;
    IF p_name !~ ('^' || p_parent || '_[a-z0-9_]+$') THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('partition name %s must start with %s_', p_name, p_parent);
    END IF;
    IF to_regclass(format('%I.%I', v_schema, p_name)) IS NOT NULL THEN
        RETURN false;
    END IF;
    EXECUTE format('CREATE TABLE %I.%I (LIKE %I.%I INCLUDING DEFAULTS INCLUDING CONSTRAINTS)', v_schema, p_name, v_schema, p_parent);
    RETURN true;
END;
$$;

-- thaw, step 2: seal the loaded table (read-only from now on) and attach it as the RANGE partition
-- [p_from, p_to), or, with p_value, as the LIST partition for p_value; idempotent. Re-freezing a
-- thawed unit at the end of its window drops it with besdk_drop_partition (its cold copy stays).
CREATE OR REPLACE FUNCTION besdk_thaw_attach(p_parent text, p_name text, p_from timestamptz, p_to timestamptz, p_value text DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS $$
DECLARE
    v_schema text := current_schema();
    v_part   regclass := to_regclass(format('%I.%I', current_schema(), p_name));
BEGIN
    IF v_part IS NULL OR p_name !~ ('^' || p_parent || '_[a-z0-9_]+$') THEN
        RAISE EXCEPTION USING ERRCODE = '42P01', MESSAGE = format('%s is not a thawed table of %s', p_name, p_parent);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_inherits i WHERE i.inhrelid = v_part) THEN
        RETURN false;
    END IF;
    PERFORM besdk_seal_table(p_name);
    IF p_value IS NULL THEN
        EXECUTE format('ALTER TABLE %I.%I ATTACH PARTITION %I.%I FOR VALUES FROM (%L) TO (%L)', v_schema, p_parent, v_schema, p_name, p_from, p_to);
    ELSE
        EXECUTE format('ALTER TABLE %I.%I ATTACH PARTITION %I.%I FOR VALUES IN (%L)', v_schema, p_parent, v_schema, p_name, p_value);
    END IF;
    RETURN true;
END;
$$;
