// The third part of the platform migration (P11.3, P12.4, P12.5): the event streams and the component's durables
// exist after `migrate up`. Subjects come from component.yaml's `events` block (generated by be-ops, P12.16).
import type { Logger } from "pino";
import type { Config } from "../config/config.js";
import type { Manifest } from "../config/manifest.js";
import { JetStreamBus } from "./bus/jetstream.js";
import { durableName } from "./names.js";

const CONNECT_TIMEOUT_MS = 30_000;

export async function ensureEventsAtMigrate(memberId: string, manifest: Manifest, config: Config, logger: Logger): Promise<void> {
  const subjects = [...manifest.publishes, ...manifest.subscribes.filter((s) => !s.endsWith("*"))];
  if (subjects.length === 0) return;
  const has = (k: string) => config.declares(k) && config.has(k);
  const url = has("EVENT_BUS_URL") ? config.string("EVENT_BUS_URL") : has("NATS_URL") ? config.string("NATS_URL") : undefined;
  if (!url?.startsWith("nats://")) {
    logger.warn({ url: url ?? null }, "no JetStream bus configured: streams and durables are created at start");
    return;
  }
  let timer: NodeJS.Timeout | undefined;
  const bus = await Promise.race([
    JetStreamBus.connect({ url, name: `${memberId}/migrate`, logger }),
    new Promise<never>((_, rej) => (timer = setTimeout(() => rej(new Error(`the bus at ${url} is not reachable`)), CONNECT_TIMEOUT_MS))),
  ]).finally(() => clearTimeout(timer));
  try {
    for (const s of subjects) await bus.ensureStream(s);
    for (const s of manifest.subscribes.filter((x) => !x.endsWith("*"))) await bus.ensureDurable(durableName(memberId, s), s);
  } finally {
    await bus.close();
  }
}
